version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
